
package com.web.service.implementation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MovieManagerService", targetNamespace = "http://Implementation.service.web.com/", wsdlLocation = "file:/E:/Concordia/Winter%202023/DSD/Assignments/Assignemnt_3_web_Service/DMTBS_WS/DMTBS_WS/src/Resources/MovieManagerService.wsdl")
public class MovieManagerService
    extends Service
{

    private final static URL MOVIEMANAGERSERVICE_WSDL_LOCATION;
    private final static WebServiceException MOVIEMANAGERSERVICE_EXCEPTION;
    private final static QName MOVIEMANAGERSERVICE_QNAME = new QName("http://Implementation.service.web.com/", "MovieManagerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/E:/Concordia/Winter%202023/DSD/Assignments/Assignemnt_3_web_Service/DMTBS_WS/DMTBS_WS/src/Resources/MovieManagerService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MOVIEMANAGERSERVICE_WSDL_LOCATION = url;
        MOVIEMANAGERSERVICE_EXCEPTION = e;
    }

    public MovieManagerService() {
        super(__getWsdlLocation(), MOVIEMANAGERSERVICE_QNAME);
    }

    public MovieManagerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MOVIEMANAGERSERVICE_QNAME, features);
    }

    public MovieManagerService(URL wsdlLocation) {
        super(wsdlLocation, MOVIEMANAGERSERVICE_QNAME);
    }

    public MovieManagerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MOVIEMANAGERSERVICE_QNAME, features);
    }

    public MovieManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MovieManagerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebInterface
     */
    @WebEndpoint(name = "MovieManagerPort")
    public WebInterface getMovieManagerPort() {
        return super.getPort(new QName("http://Implementation.service.web.com/", "MovieManagerPort"), WebInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebInterface
     */
    @WebEndpoint(name = "MovieManagerPort")
    public WebInterface getMovieManagerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Implementation.service.web.com/", "MovieManagerPort"), WebInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MOVIEMANAGERSERVICE_EXCEPTION!= null) {
            throw MOVIEMANAGERSERVICE_EXCEPTION;
        }
        return MOVIEMANAGERSERVICE_WSDL_LOCATION;
    }

}
